steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build','-t','gcr.io/direct-tribute-368812/go_gbuild_cicd:latest', '-t', 'gcr.io/direct-tribute-368812/go_gbuild_cicd:$SHORT_SHA','.']

    - name: 'docker'
      args: ['run','-d','--name','goapp','gcr.io/direct-tribute-368812/go_gbuild_cicd:latest']

    - name: 'docker'
      args: ['exec','goapp','go','test']

    - name: 'docker'
      args: ['push','gcr.io/direct-tribute-368812/go_gbuild_cicd:latest']

    - name: 'docker'
      args: ['push','gcr.io/direct-tribute-368812/go_gbuild_cicd:$SHORT_SHA']

    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run','deploy','go-cloudrun','--image','gcr.io/direct-tribute-368812/go_gbuild_cicd:$SHORT_SHA','--region','us-central1','--platform','managed','--allow-unauthenticated']
